version: "3.8"
services:
  ddb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
     - ./dynamodb_data:/home/dynamodblocal/data
    ports:
      - 8000:8000